### ISSUE TITLE
Blocking malformed request headers

### ISSUE THREAD

**Issue by vladtcvs** [tempesta-tech/tempesta#1050]
Requests with the following malformed headers are normally passed to a backend or serviced from the cache. Historically, we just validate allowed alphabets for headers which we don't use.

Accept:

https://tools.ietf.org/html/rfc7231#section-5.3.2

```
GET / HTTP/1.1
Host: localhost
Accept: invalid
```

Accept-Charset:

https://tools.ietf.org/html/rfc7231#section-5.3.3
https://tools.ietf.org/html/rfc6365#section-2

Charset names are registered by the IANA according to procedures documented in      [RFC2978]. <RFC6365>

```
GET / HTTP/1.1
Host: localhost
Accept-Charset: invalid
```

Accept-Encoding:

https://tools.ietf.org/html/rfc7231#section-3.1.2.1

```
GET / HTTP/1.1
Host: localhost
Accept-Encoding: invalid
```

Accept-Language:

https://tools.ietf.org/html/rfc4647#section-2.1

```
GET / HTTP/1.1
Host: localhost
Accept-Language: 123456789
```

Content-Encoding:

https://tools.ietf.org/html/rfc7231#section-3.1.2.1
https://tools.ietf.org/html/rfc7231#section-8.4

```
POST / HTTP/1.1
Host: localhost
Content-Encoding: invalid
Content-Length: 0
```

Content-Language:

https://tools.ietf.org/html/rfc4647#section-2.1

```
POST / HTTP/1.1
Host: localhost
Content-Language: 123456789
Content-Length: 0
```

Content-Location:

https://tools.ietf.org/html/rfc7231#section-3.1.4.2

```
POST / HTTP/1.1
Host: localhost
Content-Location: not a uri
Content-Length: 0
```

Content-Range:

https://tools.ietf.org/html/rfc7233#section-4.2

```
POST / HTTP/1.1
Host: localhost
Content-Range: invalid
Content-Length: 0
```

Content-Type:

https://tools.ietf.org/html/rfc7231#section-3.1.1.1

```
POST / HTTP/1.1
Host: localhost
Content-Type: invalid
Content-Length: 0
```

Date:

https://tools.ietf.org/html/rfc7231#section-7.1.1.1

```
GET / HTTP/1.1
Host: localhost
Date: invalid
```

Expect:

https://tools.ietf.org/html/rfc7231#section-5.1.1

```
GET / HTTP/1.1
Host: localhost
Expect: invalid
```

```
GET / HTTP/1.1
Host: localhost
Expect: 100-continue
```

From:

https://tools.ietf.org/html/rfc5322#section-3.4
https://tools.ietf.org/html/rfc5322#section-3.4.1

```
GET / HTTP/1.1
Host: localhost
From: not a email
```

If-None-Match:
If-Match:
If-Range:

https://tools.ietf.org/html/rfc7232#section-2.3
https://tools.ietf.org/html/rfc7232#section-3.1

```
GET / HTTP/1.1
Host: localhost
If-Match: not in quotes
Content-Length: 0
```

```
GET / HTTP/1.1
Host: localhost
If-None-Match: not in quotes
Content-Length: 0
```

```
GET / HTTP/1.1
Host: localhost
If-Range: not in quotes
Content-Length: 0
```

If-Unmodified-Since:
If-Modified-Since:

https://tools.ietf.org/html/rfc7231#section-7.1.1.1

```
GET / HTTP/1.1
Host: localhost
If-Modified-Since: invalid
Content-Length: 0
```

```
GET / HTTP/1.1
Host: localhost
If-Unmodified-Since: invalid
Content-Length: 0
```

Last-Modified:

https://tools.ietf.org/html/rfc7232#section-2.2

```
POST / HTTP/1.1
Host: localhost
Last-Modified: invalid
Content-Length: 0
```

Max-Forwards:

https://tools.ietf.org/html/rfc7231#section-5.1.2

```
GET / HTTP/1.1
Host: localhost
Max-Forwards: not a number
```

Range:

https://tools.ietf.org/html/rfc7233#section-3.1

```
GET / HTTP/1.1
Host: localhost
Range: invalid
```

Transfer encoding:

https://tools.ietf.org/html/rfc7230#section-4
https://tools.ietf.org/html/rfc7230#section-8.4

```
GET / HTTP/1.1
Host: localhost
Transfer-Encoding: invalid
```

**Comment by krizhanovsky** [comment]
As for #1053, even #1131 fix, it's still not wished to grow the parser state machine due to lower performance and more DoS opportunities. Meantime it's still wished to filter the headers content which is in most cases just directly passed to an application. Unfortunately even with the strict RFC validation we still can not fully solve several injection attacks, like [RCE in User-Agent](https://www.dropbox.com/s/om4yttb6nfix2hk/BSidesAth16_Perform_Effective_Command_Injection_Attacks_Like_Mr.Robot_Final.pdf), so in general the task just slows the things down and doesn't solve any real security issue. In general there are headers which we already parse, but do this inaccurately and this must be fixes. Next, we should validate only security crucial headers. So I close the task aggregating all the headers issues and open new issues with specific tasks and headers (also we have issues on `Content-Type`):

- Content-Type - #901 and #1119 
- date-related headers (If-Modifies-Since, Expires, Date, If-Modified) - #1202 
- Accept - #1203
