### ISSUE TITLE
 Blocking malformed response headers

### ISSUE THREAD

**Issue by vladtcvs** [tempesta-tech/tempesta#1053]
This malformed responses leads to 200 response from tempesta
https://tools.ietf.org/html/rfc7233#section-2.3

```
HTTP/1.1 200 OK
Accept-Ranges: invalid
Content-Length: 0
Connection: close
```

https://tools.ietf.org/html/rfc7231#section-7.1.2
```
HTTP/1.1 200 OK
Location: not a uri
Content-Length: 0
Connection: close
```

https://tools.ietf.org/html/rfc7231#section-7.1.3
```
HTTP/1.1 200 OK
Retry-After: not a date
Content-Length: 0
Connection: close
```

https://tools.ietf.org/html/rfc7233#section-2.3

```
HTTP/1.1 200 OK
Accept-Ranges: invalid
Content-Length: 0
```

https://tools.ietf.org/html/rfc7231#section-3.1.2.1
https://tools.ietf.org/html/rfc7231#section-8.4
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Encoding: invalid
```

https://tools.ietf.org/html/rfc4647#section-2.1

```
HTTP/1.1 200 OK
Content-Length: 0
Content-Language: 123456789
```

https://tools.ietf.org/html/rfc7231#section-3.1.4.2
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Location: not a uri
```

https://tools.ietf.org/html/rfc7233#section-4.2
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Range: invalid
```

https://tools.ietf.org/html/rfc7231#section-3.1.1.1

```
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: invalid
```

https://tools.ietf.org/html/rfc7231#section-7.1.1.1
```
HTTP/1.1 200 OK
Content-Length: 0
Date: not a date
```

https://tools.ietf.org/html/rfc7234#section-5.3
```
HTTP/1.1 200 OK
Content-Length: 0
Expires: not a date
```

https://tools.ietf.org/html/rfc7232#section-2.2
```
HTTP/1.1 200 OK
Content-Length: 0
Last-Modified: not a date
```

https://tools.ietf.org/html/rfc7231#section-7.1.2
```
HTTP/1.1 200 OK
Location: not a uri
Content-Length: 0
```

https://tools.ietf.org/html/rfc7231#section-7.1.3
```
HTTP/1.1 200 OK
Retry-After: not a date
Content-Length: 0
```

**Comment by ikoveshnikov** [comment]
This four headers (`Accept-Ranges`, `Allow`, `Location`, `Retry-After`) are not parsed and sanitised inside TempestaFW, only generic alphabet checking is performed. Thus none of this responses are dropped or blocked as invalid.

What exactly happens - your test is completely wrong. Take a look to your responses: neither `Transfer-Encoding` not `Content-Length` headers are provided. That means that response ends only when backend server closes the connection to the TempestaFW. I've tried to run the test, but it seems to be broken or not stable at the moment (see output below). So i've looked though the tests: the backend connection is not closed. Tempesta caches the given response until it's end, but it never ends, that's why you don't see any responses on client side.

Secondly, `Connection: close` header means that connection betwen _backend and Tempesta_ will be closed once the message will be received by TempestaFW. It doesn't cause connection close between TempestaFW and it's client.

I've raised the question several times during tests reviews: add only required and necessary headers. TempestaFW uses a lot of headers and it's behaviour differs depending on the headers set. Sometimes there can be several variants like use `Transfer-Encoding`, or `Content-Length` or none of them. Generic rule is simple: use most common case. In this particular case `connection: close` header should be removed and `Content-Length` header is missing.

Related to #1050.

**Comment by vladtcvs** [comment]
https://tools.ietf.org/html/rfc7233#section-2.3

```
HTTP/1.1 200 OK
Accept-Ranges: invalid
Content-Length: 0
```

https://tools.ietf.org/html/rfc7231#section-3.1.2.1
https://tools.ietf.org/html/rfc7231#section-8.4
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Encoding: invalid
```

https://tools.ietf.org/html/rfc4647#section-2.1

```
HTTP/1.1 200 OK
Content-Length: 0
Content-Language: 123456789
```

https://tools.ietf.org/html/rfc7231#section-3.1.4.2
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Location: not a uri
```

https://tools.ietf.org/html/rfc7233#section-4.2
```
HTTP/1.1 200 OK
Content-Length: 0
Content-Range: invalid
```

https://tools.ietf.org/html/rfc7231#section-3.1.1.1

```
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: invalid
```

https://tools.ietf.org/html/rfc7231#section-7.1.1.1
```
HTTP/1.1 200 OK
Content-Length: 0
Date: not a date
```

https://tools.ietf.org/html/rfc7234#section-5.3
```
HTTP/1.1 200 OK
Content-Length: 0
Expires: not a date
```

https://tools.ietf.org/html/rfc7232#section-2.2
```
HTTP/1.1 200 OK
Content-Length: 0
Last-Modified: not a date
```

https://tools.ietf.org/html/rfc7231#section-7.1.2
```
HTTP/1.1 200 OK
Location: not a uri
Content-Length: 0
```

https://tools.ietf.org/html/rfc7231#section-7.1.3
```
HTTP/1.1 200 OK
Retry-After: not a date
Content-Length: 0
```

**Comment by vladtcvs** [comment]
Update original message

**Comment by krizhanovsky** [comment]
The first thing is that in most cases we trust our backends except cases when the backends are successfully attacked or specific environments with requirement of defence in depth, e.g. microservices (#1084). In the cases it makes sense to block such responses to mitigate the attack impact on clients or other microservices.

The second thing, the same as for #1050, is that not all malformed requests are actually harmful, so we easily spend resources on the headers validation (BTW enhancing DDoS attack leverage) and do not seriously improve the application security.

In any case response validation is the subject for large WAFs and this is not a job for a WAF accelerator.
