### ISSUE TITLE
Possible unsigned overflows in session life time calculation

### ISSUE THREAD

**Issue by i-rinat** [tempesta-tech/tempesta#1091]
There is a possible unsigned overflow in `sv.ts + tfw_cfg_sticky.sess_lifetime * HZ` ([link](https://github.com/tempesta-tech/tempesta/blob/ed82007d064a01c45a8378f4c6c75e1f784e4866/tempesta_fw/http_sess.c#L974)). Type of `tfw_cfg_sticky.sess_lifetime` is `unsigned int`. Multiplying by `HZ` may result in value larger that `unsigned int` may represent. That reduces "infinite" session life time from ~136 years to about ~50 days.

These [1] overflows need to be addressed in both `master` branch and 0.5 release branch.

[1] There are could other cases too. Search for "HZ" string in the code.

**Comment by ikoveshnikov** [comment]
There can be more cases, not only when `HZ` is involved. Need to look though all configuration directives with integer values and limit upper (and lower) borders to prevent overflows.

**Comment by ikoveshnikov** [comment]
Also ternary operation is not required here:

https://github.com/tempesta-tech/tempesta/blob/ed82007d064a01c45a8378f4c6c75e1f784e4866/tempesta_fw/http_sess.c#L973-L975

Since ` tfw_cfg_sticky.sess_lifetime` is never equals to `0`:
https://github.com/tempesta-tech/tempesta/blob/ed82007d064a01c45a8378f4c6c75e1f784e4866/tempesta_fw/http_sess.c#L1255-L1260
