### ISSUE TITLE
Process the `Pragma` header field

### ISSUE THREAD

**Issue by avbelov23** [tempesta-tech/tempesta#1116]
Tempesta FW parses the `Pragma` header field in the request (correctly), but the cache (`tfw_cache_employ_resp()`) expects the  `Pragma` header field in the response (incorrect).
RFC 7231 mention `Pragma` only as the header field of the request.

**Comment by ikoveshnikov** [comment]
I've done a little bit of searching about `Pragma` header. `Pragma: no-cache` was never intended to be used in responses, not only for [HTTP.1/1](https://tools.ietf.org/html/rfc7234#section-5.4), but even in [HTTP/1.0](https://tools.ietf.org/html/rfc1945#section-10.12). Latest RFCs has a [special warning](https://tools.ietf.org/html/rfc7234#section-5.4) about it:
> Note: Because the meaning of "Pragma: no-cache" in responses is
      not specified, it does not provide a reliable replacement for
      "Cache-Control: no-cache" in them.

Several [sources](https://www.fastly.com/blog/headers-we-dont-want) tell about misusing of  `Pragma: no-cache` if responses. But advices to _use_ the header in the responses for compatibility with HTTP/1.0 clients can be easily found. E.g. there was a short dispute on [Stackoverflow](https://stackoverflow.com/questions/10314174/difference-between-pragma-and-cache-control-headers) about the issue. It's very very odd to hear about misuse of outdated header, bit it's how the thing happened.

But Tempesta doesn't account the `Pragma: no-cache` in responses. The issue is about this lines:
https://github.com/tempesta-tech/tempesta/blob/ac3aebae3378310f6ee883bff844eeb45498846b/tempesta_fw/cache.c#L412-L414
Actually `TFW_HTTP_CC_PRAGMA_NO_CACHE` flag is set only for requests, see `http_parser.c`. The RFC says about `Pragma: no-cache` header:
> When the Cache-Control header field is not present in a request,
   caches MUST consider the no-cache request pragma-directive as having
   the same effect as if "Cache-Control: no-cache" were present (see
   Section 5.2.1).

Seems like `resp` is misused in the code above, and `req` must be used there.

**Comment by i-rinat** [comment]
As for `Pragma: no-cache` in response headers,

**Firefox** (current mercurial tip) recognizes and uses `Pragma: no-cache` in response:
```c++
void
nsHttpResponseHead::ParsePragma(const char *val)
{
    LOG(("nsHttpResponseHead::ParsePragma [val=%s]\n", val));

    if (!(val && *val)) {
        // clear no-cache flag
        mPragmaNoCache = false;
        return;
    }

    // Although 'Pragma: no-cache' is not a standard HTTP response header (it's
    // a request header), caching is inhibited when this header is present so
    // as to match existing Navigator behavior.
    if (nsHttp::FindToken(val, "no-cache", HTTP_HEADER_VALUE_SEPS))
        mPragmaNoCache = true;
}
```
(It's then used in expression `(mCacheControlNoCache || mPragmaNoCache)`).

Similarly, **Chromium**/**Chrome** (70.0.3538.110) also checks `Pragma: no-cache` in responses:
```c++
HttpResponseHeaders::FreshnessLifetimes
HttpResponseHeaders::GetFreshnessLifetimes(const Time& response_time) const {
  FreshnessLifetimes lifetimes;
  // Check for headers that force a response to never be fresh.  For backwards
  // compat, we treat "Pragma: no-cache" as a synonym for "Cache-Control:
  // no-cache" even though RFC 2616 does not specify it.
  if (HasHeaderValue("cache-control", "no-cache") ||
      HasHeaderValue("cache-control", "no-store") ||
      HasHeaderValue("pragma", "no-cache")) {
    return lifetimes;
  }
  ...
```

**Varnish** ignores `Pragma` in responses, although mentions how to use it if desired:
```
Pragma
~~~~~~

An HTTP 1.0 server might send the header ``Pragma: nocache``. Varnish ignores this
header. You could easily add support for this header in VCL.

In `vcl_backend_response`::

    if (beresp.http.Pragma ~ "nocache") {
        set beresp.uncacheable = true;
        set beresp.ttl = 120s; # how long not to cache this url.
    }
```

**Nginx** ignores Pragma, as there are no even mentions of the "pragma" substring in the code.

**Comment by i-rinat** [comment]
I believe that while adding pragma-no-cache support for requests, as mentioned in RFC, we should keep pragma-no-cache support in responses.

Some software (see https://github.com/tempesta-tech/tempesta/issues/1116#issuecomment-441797610) perhaps for compatibility reasons still recognize "`pragma: no-cache`" in response headers. There may be some applications relying on that. If that's some unlikely case of an old application which relies on "pragma" exclusively, failing to recognize the field may cause caching where caching was prohibited.
