### ISSUE TITLE
any production users for this firewall?

### ISSUE THREAD

**Issue by hiqsociety** [tempesta-tech/tempesta#1774]
great work by the way, it's really amazing piece of work.
1. any production user?
2. i'm basically just waiting for http2 to be out. kernel modification needed? if so, which OS is supported? i'm mainly into ubuntu 22.04. possible to make it the standard supported OS because it's really very much popular for cloud providers everywhere now.

**Comment by krizhanovsky** [comment]
Hi @hiqsociety ,

thank you for you questions.

> any production user?

We have couple of OEM cases where Tempesta FW's reduced functionality is used in pre-production.

>  kernel modification needed? 

Yes. The current patch is available at https://github.com/tempesta-tech/tempesta/blob/master/linux-5.10.35.patch or you can use already patched kernel https://github.com/tempesta-tech/linux-5.10.35-tfw .

> if so, which OS is supported? i'm mainly into ubuntu 22.04. possible to make it the standard supported OS because it's really very much popular for cloud providers everywhere now.

Yeah, Ubuntu 22 is also the primary distro for us.

**Comment by ultperf** [comment]
@krizhanovsky thank you for your response.
looking forward to http2 in the milestone. in fact, i'm looking at it daily.

last question.

possible to explore using bpf completely? 
i saw some code not sure if it'll be truly 100% bpf so we dont have to patch the kernel.
maybe just limiting the kernel modification to unlimited (or as much as possible) instructions instead of 1mil instructions for bpf program will do i guess?

learning to code in bpf and has written some small programs so can contribute code too if so.

**Comment by krizhanovsky** [comment]
Hi @ultperf ,

in our patch we mostly modify the Linux kernel code (e.g. introduce pure page allocator for skb) and open some symbols for usage from GPLv2 code - these things aren't doable with BPF. However, we do plan to implement the set of hooks that you can write BPF rules to work with HTTP traffic on wire speed (see https://github.com/tempesta-tech/tempesta/issues/102)

**Comment by hiqsociety** [comment]
@krizhanovsky thank you.
