### ISSUE TITLE
possible to update the due date to a more practical one?

### ISSUE THREAD

**Issue by hiqsociety** [tempesta-tech/tempesta#1776]
was following this daily since early Dec. please update this timeline so at least we know etc.
https://github.com/tempesta-tech/tempesta/milestone/15

**Comment by krizhanovsky** [comment]
Definitely makes sense, @const-t @s0nx we need to discuss this on the first meetings in '23.

**Comment by krizhanovsky** [comment]
Hi @hiqsociety ,

we split the 0.7 milestone into two parts:
1. https://github.com/tempesta-tech/tempesta/milestone/15 , due to March 31. This will be the beta - all crucial bugs will be fixed in HTTP/2 and our web site must also work on HTTP/2.
2. https://github.com/tempesta-tech/tempesta/milestone/11, due to September 1 (may change). This will be 1.0 GA with all known bugs fixed.

**Comment by krizhanovsky** [comment]
I close the issue for now. Please don't hesitate to reopen it if there is any question.
