### ISSUE TITLE
`block_action` does not work for h2 as expected

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1819]
#### [Current documentation](https://github.com/tempesta-tech/tempesta/wiki/Handling-clients#error-responses):
> drop - Tempesta FW must block message silently (response won't be generated) and reset (with TCP RST) the client connection.

>  reply - Response with appropriate error status will be sent to client, a TCP connection remains open or closed according to the normal HTTP connection handling rules.

The main problem - RST_STREAM. 
Now I receive RST_STREAM + FIN TCP for config `block_action error drop` and parsing error (by RFC - RST_STREAM does not close coonection). But by documentation - TCP RST. And also I does not receive RST_STREAM for `block_action error reply` and parsing error - only 400 Bad Request.

#### For h2 connection, I think it should work as follows:

- `block_action attack/error drop` - Tempesta send only TCP RST. No RST_STREAM, GOAWAY, 400 Bad Request or other.
- `block_action attack/error reply` - Tempesta send 400 Bad Request (or other status) and then RST_STREAM or GOAWAY ([See RFC](https://www.rfc-editor.org/rfc/rfc9113.html#name-goaway)). And also Tempesta must not send TCP FIN for `reply` and RST_STREAM.

**Comment by krizhanovsky** [comment]
https://www.rfc-editor.org/rfc/rfc9113.html#section-6.8-6 states
> An endpoint might choose to close a connection without sending a GOAWAY for misbehaving peers.

Also there is no any MUST statement about sending `RST_STREAM` in https://www.rfc-editor.org/rfc/rfc9113.html#name-rst_stream , so I agree with
> `block_action attack/error drop` - Tempesta send only TCP RST. No RST_STREAM, GOAWAY, 400 Bad Request or other.

`block_action attack reply` means that we shall send an HTTP response to a malicious client (typically for traceability and/or in case of a false positive), but the peer is still malicious and we should close the whole TCP connection with it. One of obvious example is reaching connections limit with this configuration option. Since TCP RST doesn't work with data transmission, we should close TCP connection with normal TCP FIN. It seems from the RFC 9113 6.8 that we should use `GOAWAY` to shutdown the whole connection.

I think `block_action error reply` should send an HTTP error response and do `RST_STREAM` just to reset the problem stream and let the client to use other streams and establish a new one instead of just reseted one.

**Comment by EvgeniiMekhanik** [comment]
I see some problem here with `block_action error reply`. For some parsing errors we should also drop connection and send goaway (now we consider all parses errors as `error` not `attack` case).
