### ISSUE TITLE
Tempesta-fw 2-clients Cache bug

### ISSUE THREAD

**Issue by pale-emperor** [tempesta-tech/tempesta#1844]
# Motivation

For now we got unexpected behavior with `cache 2` directive 

# Scope

Client 1 visit page - works fine
When second client visits same page - it breaks cache work. from that moment Client 1 will receive cached version of page and PURGE will not refresh it.

How to reproduce:
Restart tempesta on tempesta-tech.com
Visit: https://tempesta-tech.com/blog/nginx-tail-latency from any browser-1 and leave a comments 1,2
Visit same page with different browser and leave comment 3

result:
Browser 2 will show 3 comment
Browser 1 will show comments 1+2 only. Other comments will not show on this client, `curl -X PURGE` will also not work

**Comment by krizhanovsky** [comment]
Agreed to make a per-location cache configuration option fort he default max-age

**Comment by krizhanovsky** [comment]
@dmpetroff probably a better (more consistent with the current abilities) approach would be to extend `$cache` option to accept number of seconds to keep a resource in the cache instead of just `0`/`1`. Instead of locations, we can write HTTP tables rules like:
```
uri == "/knowledge-base/*" -> $cache = 60;
```

See https://github.com/tempesta-tech/tempesta/wiki/HTTP-tables and https://github.com/tempesta-tech/tempesta/wiki/Caching-Responses

**Comment by krizhanovsky** [comment]
Please also update https://github.com/tempesta-tech/tempesta/wiki/HTTP-tables and https://github.com/tempesta-tech/tempesta/wiki/Caching-Responses wiki pages and all the tests using `$cache`.

**Comment by krizhanovsky** [comment]
Done in #1851
