### ISSUE TITLE
frang: parsing of request method with TCP segmentation

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1872]
# Scope
For frang config:
```
frang_limits {
    http_methods get post;
}
```
Send GET or POST request with TCP segmentation 1 byte:
AR: Tempesta returns 403 response and dmesg warning `frang: restricted HTTP method for 127.0.0.1: 17 (0x20000u)`;
ER: Tempesta forwards request to server;

# Testing
`t_frang.test_http_methods.FrangHttpMethodsTestCase` and `t_frang.test_http_method_override_allowed.FrangHttpMethodsOverrideTestCase` with -T 1 option

**Comment by EvgeniiMekhanik** [comment]
There are two different cases here:
1. We should not pass not fully parsed HTTP method to frang check (frang should check this case and return without block).
2. There is a case when we have invalid request with UNKNOWN method or some other method blocked by frang. In case when we deal with TCP segmentation we have frang error, otherwise parser error. It is not a problem, we should write a valid test for this.
