### ISSUE TITLE
Tempesta health statistics bugs

### ISSUE THREAD

**Issue by voodam** [tempesta-tech/tempesta#2036]
Inherited from https://github.com/tempesta-tech/tempesta/issues/1454

## Negative values in statistics

At the current master as the date of the issue I observe negative values in the statistics, when only couple of requests were processed by Tempesta (observed for the first line only):
```# cat /proc/tempesta/servers/default/127.0.0.1\:9090 
Minimal response time		: -1ms
Average response time		: 0ms
Median  response time		: 0ms
Maximum response time		: 0ms
```

One more backend server statistics issue taken from the production server:
```
root@tempesta-1:/proc/tempesta# cat servers/default/192.168.122.1 
Minimal response time		: 0ms
Average response time		: 93ms
Median  response time		: 1ms
Maximum response time		: 1960ms
Percentiles
50%:	1ms
75%:	1ms
90%:	256ms
95%:	2749ms
99%:	2749ms
```
Obviously maximum response time can not be smaller than 99 or 95 percentiies.

## Hung socket buffers

The same number of socket buffers may appear in the site statistics for relatively long time, which looks fishy (our web site statistics):
```
# for i in `seq 1 10`; do grep 'Socket buffers in flight' perfstat ; sleep 1; done
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
Socket buffers in flight		: 49
```

**Comment by kingluo** [comment]
```
root@tempesta-1:/proc/tempesta# cat servers/default/192.168.122.1 
Minimal response time		: 0ms
Average response time		: 93ms
Median  response time		: 1ms
Maximum response time		: 1960ms
Percentiles
50%:	1ms
75%:	1ms
90%:	256ms
95%:	2749ms
99%:	2749ms
```

The maximum response time is the real collected time, but those shown in the percentiles are not. Instead, they're scaled for optimization, so they may be aligned to be larger than the real one.

https://github.com/tempesta-tech/tempesta/blob/b39ce95f0c5ab3386c3a618bce9f49fcb1888060/fw/apm.c#L733C1-L741C3

```c
        for (r = i / TFW_STATS_BCKTS; r < TFW_STATS_RANGES; ++r) {
                for (b = i % TFW_STATS_BCKTS; b < TFW_STATS_BCKTS; ++b, ++i) {
                        if (!rng->cnt[r][b])
                                continue;
                        rtt = rng->ctl[r].begin + (b << rng->ctl[r].order);
                        __tfw_apm_state_set(st, rtt, i, r, b);
                        return;
                }
        }
```

**Comment by krizhanovsky** [comment]
Probably the percentiles bug should be fixed with a probabilistic algorithm like [count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) and maybe this should be done in #712

**Comment by kingluo** [comment]
The current design principles are:

It has 4 ranges to collect rtt samples, each range has 16 buckets, and then the actual rtt values will be mapped to `(range, bucket)`. Note that the last range may be expanded to include larger values. "Extending" here does not mean increasing the array or bucket, but adjusting the parameters: "begin, end, order" to ensure that larger values can be projected into this range.

```
order:         0      1      2       4
begin..end: |1..16|17..47|48..108|109..349|
```

When calculating a histogram, each percentage boundary is determined based on the cumulative count from left to right.

On the other hand, the time window and scaling value in the configuration file are used to determine whether the histogram needs to be updated to avoid frequent updates.

Now we know why the histogram may not match the maximum value, because the bounds are a logical approximation and it may be larger than the maximum value.

So the solution is to use max as the histogram value if approx is greater than max.

Example:

```
Minimal response time           : 60ms
Average response time           : 1400ms
Median  response time           : 1133ms
Maximum response time           : 2572ms
Percentiles
50%:    1133ms
75%:    1901ms
90%:    2572ms
95%:    2572ms
99%:    2572ms
```
