### ISSUE TITLE
Tempesta automatic reboot and crash dump

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#251]
Best practice and configuration HOWTOs must be developed to make Tempesta-enabled Linux kernel automatically reboot on crash and produce dumps for bug reporting and analyzing. The best practice and HOWTO must be added to README.md as separate chapter.

**Comment by milabs** [comment]
We should consider of using exception handling while doing in kernel mode.

## Native kernel approach (extables)

Linux kernel has limited exception model which allows user to handle faults on certain instructions. Every such an instruction's address needs to be handled via the `extable`. So, to catch the fault we must known for sure which the instruction may cause the fault and fill `extable` item with the instruction address and the fixup pointer. The latter is the address of the first instruction which takes the control after the fault.

One of the possible solutions is to fill Tempesta's module `extabe` in run-time with instruction ranges and specify fixup address for each range. So, let's assume that protected function looks like this:

```
<func>:
    insn1
    insn2
    ...
    insnN
    ret
```

In such a case we'll need to fill `extable` with every instruction address and specify the same `fixup` for all of them. So, `fixup` get's the control if some of the insn's causes fault.

There are many limitations of using such a technique. Except that module's `extable` going huge, there is a problem with `fixup` point by itself. It's required for the `fixup` to be in the context as the guarded `function`. Otherwise, `fixup` will have problems accessing the function variables.

For the example of using `extable` with kernel modules one can see that link:
https://github.com/milabs/kmod_extable

## SEH-implementation

Windows has a great exception handling approach - SEH (Structured Exception Handling). The main idea is to use a chain if exception handlers. 

- The exception handlers are linked to each other
- They form a linked list chain on the stack, and sit relatively close to the bottom of the stack
- When an exception occurs, Windows retrieves the head of the SEH chain SEH chain walks through the list and tries to find the suitable handler to close the application properly

As for now, Linux kernel doesn't have ad ability to implement SEH without extending the kernel. Also, compiler support required to use the following code patterns:

`__try {}  __except(...) {}` and `__try {} __finally {}`

**Comment by krizhanovsky** [comment]
The technical aspect of the issue is an overengineering. Any complicated exception handling will not help against memory corruptions and we can not restore from such kinds of faults. The real solution is to minimize the kernel module, which is emphasized by #77 . The other solution is to run Tempesta FW in a VM.

Meantime, we must be able to support user incidents, so Tempesta FW's packages ( #640 ) must set sysctl for automatic system reboot on oops, install and setup [crash dump](http://www.tldp.org/HOWTO/pdf/Linux-Crash-HOWTO.pdf).
