### ISSUE TITLE
Incorrect handling of cached responses to HEAD and GET requests for the same URI.

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#416]
A client may send a HEAD method request to the server. The response is cached. The response, however, doesn't have a message body. If the client then sends a GET method request for the same URI, Tempesta returns the cached entry that consists only of the response header part, and is missing the message body that the client expects and waits for.

**Comment by ikoveshnikov** [comment]
The issue is irrelevant to a current version and already fixed.

Tempesta configuration:
    server <test-server-ip>;
    cache_methods GET HEAD;
    cache_fulfill * *;

Test steps:
1. Send `HEAD` request to Tempesta multiple times to see that request is cached by Tempesta and Tempesta requests server only once
2. Send `GET` request to Tempesta multiple times. Response must contain body and Tempesta must request test server only once
3. Repeat
