### ISSUE TITLE
Use __hdr_append() in __hdr_sub().

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#552]
`__hdr_sub()` uses the slow path when a substitute header doesn't fit in place of the original header. The slow path is a simple `__hdr_del()` followed by `__hdr_add()`. The header is deleted in the middle of the header block of a message, and then the new header is added at the end of the header block.

In extreme case we create a bunch of empty skbs in the process (see #551), and then create another skb for the substitute header.

The slow path is doing a lot of work, more that necessary.  We already have `__hdr_append()` that can be used for the substitution. Instead of complete deletion followed by a complete insertion, it's possible to overwrite part of the original header with data from the substitute header, and add a bit more room for the rest of the substitute header exactly where it is needed.

There's one little nuance in this. When the original header is a duplicate header, then only the first header is substituted, and all duplicates are deleted. Also, one could imagine an optimization that recognizes when a duplicate header immediately follows the original, and then uses the space of both headers for the substitution.

**Comment by milabs** [comment]
> Also, one could imagine an optimization that recognizes when a duplicate header immediately follows the original, and then uses the space of both headers for the substitution.

The implementation I've tried looks over-complicated because of header's `EOL` is not a part of the `TfwStr`. This leads to impossibility of reusing contiguous DUP-string without complication the logic. Also, in current implementation every DUP-string has `0` as it's length. So, total duplicate length computation is required to check if there is enough room to place source header over.
