### ISSUE TITLE
Debian package & installer script improvements

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#762]
Need to issue release packages for recent 4.9.35 migration.

**Comment by ikoveshnikov** [comment]
Recent updates in `master-next` branch in https://github.com/tempesta-tech/linux-packages repo contains recipes to build Tempesta patched 4.9.35 kernel. There are a few disabled Debian patches that cannot be applied automatically and need to be verified since Debian uses kernel 4.9.30. Also debian team has added a couple of new patches since `master-next` brach was prepared (see branch `stretch`).

Note, that linux-4.8 and linux-4.9 is divided to debian packages in a slightly different manner, so current installer script must be updated. More over, recently Tempesta used obsoleted 4.8 kernel and there no kernel recipe updates from distro team. But now we have switched to LTS kernel, so recipe updates are expected to be pretty often but not very huge. It will be nice to do a couple thing, which was not needed before:
- stabilise ABI and preserve the same ABI between recipe updates.
- distribute packets via custom repo, not by github releases. This is more natural for end user and installer script will be much easier to support.

**Comment by ikoveshnikov** [comment]
The TempestaFW installer script must warn user in an user-friendly way about unsupported architectures and architectures that doesn't support all the features. DKMS provide some messages upon errors, but some of them just offer user to read the build log.

**Comment by krizhanovsky** [comment]
RPMs are crucial since we had requests for CentOS installations.

Also need to consider using a package hosting like https://packagecloud.io/ to distribute the packages.

**Comment by krizhanovsky** [comment]
CentOS is dead. https://github.com/tempesta-tech/tempesta/issues/762#issuecomment-320683157 is addressed in https://github.com/tempesta-tech/tempesta/issues/1423 and https://github.com/tempesta-tech/tempesta/issues/762#issuecomment-315907571 is about outdated kernel versions.
