### ISSUE TITLE
Missing functional tests for scheduling

### ISSUE THREAD

**Issue by intelfx** [tempesta-tech/tempesta#811]
We need more functional tests for correct handling of various scheduling Tempesta config options:

- [x] global-to-srv_group `sched` inheriting
- [x] ratio scheduler, static mode: non-equal `weight=`
- [x] hash scheduler: include requests with different resources, check failovering more strictly (connection register must follow a self-imposed connection remove)
- [x] http scheduler: layered schedulers (http+ratio, check fair balancing inside groups)
- [x] ratio scheduler: dynamic mode
- [x] ratio scheduler: predict mode

**Comment by krizhanovsky** [comment]
While @keshonok didn't describe exact configuration and test scenario for #826, it seems that a test intensively restarting Tempesta with dynamic or predictive variant of ratio scheduler is required. @keshonok I appreciate if you can add something about the test case.

**Comment by keshonok** [comment]
The simplest configuration should cause the crash described in #826:
```
sched ratio dynamic;
server 127.0.0.1:8080;
```

It's just happened that this case was not in the tests. Default variant of ratio scheduler is static.

The reason for the crash is exactly as described there. Scheduler is attached to a server group while Tempesta is still in the configuration processing stage. When a scheduler is attached, scheduler's internal data is created. Along with that a timer is started that attempts to retrieve fresh APM stats for each server in the group. However, APM data is created at a later stage, when Tempesta is started, because the APM configuration directive is global and can be located anywhere in the configuration file. Hence, when the timer routine for a scheduler attempts to retrieve APM data, that thread crashes on a NULL pointer.
