### ISSUE TITLE
Paired request missing

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#941]
A few messages ` Warning: Paired request missing, HTTP Response Splitting attack?` may appear in long term tests. Tempesta drops the server connection on such situations. To reproduce run e.g. `sched.test_ratio.RatioStressTest` with relatively long duration. I used duration of 10 hours, first message appeared after 5 hours of testing. Total amount of messages was ~10.

In the `sched.test_ratio.RatioStressTest` failovering of backend server connections is quite aggressive: every 100 request. In the same time `sched.test_ratio.RatioPerfTest` which is more relaxed because of disabled failovering shows no such errors.

Server connections failovering must be revised.
Tested on 5abfde71530da4edd2b34c5a31de350d1f1180e8

**Comment by krizhanovsky** [comment]
It seems one probable scenario is described in comment https://github.com/tempesta-tech/tempesta/pull/884#discussion_r168962872 :

A client sends us several requests and the client connection immediately terminated. All of the requests are in fwd_queue's and are being sent to servers, reforwarded and so on until all of the receive responses. Then `tfw_http_resp_fwd()` finds empty seq_queue of the client connection and calls `ss_close_sync()` for each of the requests. All in all, we do a lot of unnecessary work.

It's OK to leave the dead requests in fwd_queue's to minimize lock contention, but it's easy and cheap to:

1. set some flag for the reuests to make them evicted from fwd_queue right they're going to be send to a server or rescheduled;
2. we don't need to call `ss_close_sync()` in `tfw_http_resp_fwd()` since all connection_error and connection_drop callbacks follow `ss_do_close()` call in sock.c, so `tfw_http_conn_cli_drop()` is always called on closed socket.
3. `tfw_http_conn_cli_drop()` should call `tfw_connection_put()` just like `tfw_sock_srv_connect_drop()` and `tfw_sock_srv_connect_failover()` do. When `tfw_http_resp_fwd()` calls `tfw_http_conn_msg_free()` for the last request referencing the client connection, the connection is freed.

**Comment by krizhanovsky** [comment]
We didn't see the problem for a while. The optimization proposal is moved to #687 as the right place for the performance improvement, not a bug.
